name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    continue-on-error: true

    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v1
    - name: ${{ matrix.os }} | ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm install
    - name: Mocha test
      run: |
        npm test
      env:
        CI: true
